### ISSUE TITLE
TYPO3 v12 compatibility

### ISSUE THREAD

**Issue by maikschneider** [maikschneider/bw_icons#1]
In TYPO3 v12 the [CKEditor was updated](https://docs.typo3.org/c/typo3/cms-core/main/en-us//Changelog/12.0/Breaking-96874-CKEditor-relatedPluginsAndConfiguration.html) to version 5 which has has a completely rewritten plugin structure.

- [ ] CKEditor v5 support

**Comment by jackd248** [comment]
Please consider to support TYPO3 v12. 🙏

**Comment by maikschneider** [comment]
Done in [version 3.0.0](https://github.com/maikschneider/bw_icons/releases/tag/3.0.0)
