### ISSUE TITLE
Explain how to restrict icon sources based on content element

### ISSUE THREAD

**Issue by xperseguers** [maikschneider/bw_icons#10]
The documentation explains how to add new source of icons, that works fine.

But I'd like in a given (custom) content element type to have only Fontawesome icons, and in another one to have only "other" sources for instance.

Using this for instance:

```
mod.tx_bwicons {
    lci = Blueways\BwIcons\Provider\FileIconProvider
    lci {
        title = Lions Clubs International
        folder = EXT:lb_design/Resources/Public/Icons/LCI
    }
}
```

All sources are always available.

Will dig into it, but documentation doesn't describe this use case so I don't know if that's a missing feature or if that's just not documented.

**Comment by maikschneider** [comment]
Hey @xperseguers! 
Currently it's only possible to change the configuration on a per page basis. Doing this per content element would be very handy - great idea! :)

I think the best way to achieve this, would be to introduce a TCA configuration for restricting the available providers.  

```
...
'icon_field' => [
     'label' => 'My Icon',
     'config' => [
        'type' => 'input',
        'renderType' => 'iconSelection',
        'iconProviders' => 'lci,secondProviderKey'
     ]
],
...
```

What do you think about this?

**Comment by xperseguers** [comment]
Yeah, that would be ideal. I thought about a TSconfig-based configuration (such as being able to override the config on a doktype/CType base) but as I see this will be a bit complex to implement.

Your idea would be much easier to implement and in the end exactly what is really needed.

**Comment by maikschneider** [comment]
Hey @xperseguers, your PR looks awesome, thank you very much! :) I'll test and try it out next week. 

I like your use case of configuring the wizard on a per element basis - I think I'll add a little example of this in the Readme - something like this:
```
$GLOBALS['TCA']['tt_content']['types']['textmedia']['columnsOverrides'] = [
   'icon_field' => [
      'iconProviders' => 'fontawesome,otherProviderKey'
   ]
];
```
Or an example for pages.. Thanks again, I'll be in touch soon!
