### ISSUE TITLE
TYPO3 10.4.36 Exception in HelperUtility on first setup

### ISSUE THREAD

**Issue by crws** [maikschneider/bw_icons#19]
After setting up the extension everything works as described except the RTE button for the icons. Clicking it causes 
"TypeError Argument 2 passed to Blueways\BwIcons\Utility\HelperUtility::__construct() must be of the type string, null given" in ext\bw_icons\Classes\Utility\HelperUtility.php line 25

This goes away and everything works if I change 

    public function __construct(int $pid, string $iconProviders = '')
    {
        $this->pid = $pid;
        $this->iconProviders = $iconProviders;
    }

to 

    public function __construct(int $pid,  $iconProviders = '')
    {
        $this->pid = $pid;
        $this->iconProviders = $iconProviders ?? '';
    }

**Comment by maikschneider** [comment]
Hey @crws, thanks for the feedback! I added a fix in version [2.1.2](https://github.com/maikschneider/bw_icons/releases/tag/v2.1.2) :)
