### ISSUE TITLE
Extension "content_blocks" and  'renderType' => 'iconSelection'

### ISSUE THREAD

**Issue by CMS-Internetsolutions** [maikschneider/bw_icons#46]
Dear developer!
Is it possible to connect the extension with the new extension content_blocks? Is something planned here in the future? 
Many thanks for the great extension!!

**Comment by maikschneider** [comment]
Hi. Sure, this extension shall work work with content_blocks. I'm a bit surprised it does not out of the box and even more that I cannot find any information about registering custom field types. Do you know what developers need to do? Or do you know an extension that extends content_blocks?

**Comment by maikschneider** [comment]
Hi @CMS-Internetsolutions,
I just tried it: Works out of the box!
```
fields:
  -
    identifier: icon
    type: Text
    renderType: iconSelection
```
Cheers

**Comment by CMS-Internetsolutions** [comment]
Thanks I will test it again in a moment!
