### ISSUE TITLE
Version 2.0.2 breaks compatibility with TYPO3 v10

### ISSUE THREAD

**Issue by xperseguers** [maikschneider/bw_icons#7]
![image](https://user-images.githubusercontent.com/646805/212340477-24ff4aae-be3a-441b-a7fd-b37f9d82fc66.png)

**Comment by maikschneider** [comment]
Oops, I published changes for upcoming v12 by accident.. I fixed it in [v2.0.3](https://github.com/maikschneider/bw_icons/releases/tag/v2.0.3), thank you!
